### ISSUE TITLE
Moin Wallet 'Out of sync'

### ISSUE THREAD

**Issue by bsouthuk** [MOIN/moin#5]
I installed my wallet as I want to transfer my moin coins from Cryptopia into the wallet so I can stake them to earn extra moin.

I am having issues though as next to Total Balance in the Overview section, it says (OUT OF SYNC) in red.

What do I need to do to fix this before transferring my moin coins across?

Thanks

Daniel

**Comment by KingCaper** [comment]
Hi Daniel. Please join our Riot channel - we'll help you get up and running.

https://riot.im/app/#/room/#moin-general:matrix.org
