### ISSUE TITLE
Wallet address not recognized

### ISSUE THREAD

**Issue by michaelgreen06** [MOIN/moin#6]
I keep creating wallet addresses for a paper wallet but none of them are recognized by the moin block explorer.

**Comment by severus-sn4pe** [comment]
Please join our Riot channel for help and advice.

https://riot.im/app/#/room/#moin-general:matrix.org

_(Are the addresses you tested still empty? Addresses only show up in the block explorer when they have balance on it. )_

**Comment by michaelgreen06** [comment]
Got it. There is a zero balance in there.

Now the problem is that I can't transfer any from cryptopia because it says
the wallet is being re-built as of march 5th

**Comment by severus-sn4pe** [comment]
Please join our Riot channel for help and advice.

https://riot.im/app/#/room/#moin-general:matrix.org
